## makeCacheMatrix does the following:
## 1. Take in a matrix 'x'
## 2. Creates an object 'm' that will later store the inverse of 'x'
## 3. Creates 4 functions that can set and get values of 'x' and 'm'
## 4. Return a list of the 4 functions

makeCacheMatrix <- function(x = matrix()) {
        ## Define an empty object that can be checked later to see if cache exists.
        ## This object will store the inverse of matrix 'x'.
        m <- NULL
        
        ## Define a function that can reset the matrix 'x' with new values from 'new_x'.
        ## The '<<-' operator is used because "new_x" is defined outside of makeCacheMatrix.
        ## Since a new 'x' is being passed, need to also reset 'm'.
        set <- function(new_x){
                x <<- new_x
                m <<- NULL
        }
        
        ## Define a function to return the values of matrix 'x'
        get <- function() {
                x
        }
        
        ## Define a function that can reset the inverse matrix 'm' with new values from a 'new_m'
        setinverse <- function(new_m) {
                m <<- new_m
        }
        
        ## Define a function to return the values of inverse matrix 'm'
        getinverse <- function() {
                m
        }
        
        ## Return list of defined functions that can be called later.
        list(
                set = set,
                get = get,
                setinverse = setinverse,
                getinverse = getinverse
        )
}


## cacheSolve does the following:
## 1. Take in a list of functions generated by makeCacheMatrix.
## 2. Check if an inverse has been calculated. If so, retrieve it.
## 3. Otherwise, calculate and return the inverse.

## Note: Even though same variable names from makeCacheMatrix are used,
## priority will be given to how they are defined in the current environment (cacheSolve).
## In this function, 'x' is actually the list of functions generated by makeCacheMatrix.

cacheSolve <- function(x, ...) {
        ## Use the getinverse() function in 'x' to define the inverse matrix 'm'.
        ## If inverse has never been calculated, getinverse() will return NULL.
        ## If inverse has been calculated, then getinverse() will pass in cached 'm'.
        m <- x$getinverse()
        
        ## Check if inverse has been calculated (i.e. not NULL),
        ## If so then return a message and the cached 'm'.
        if(!is.null(m)){
                message("Getting cached data...")
                return(m)
        }
        
        ## Otherwise, return a message and use the get() function in 'x'
        ## to pass in the original matrix used for makeCacheMatrix.
        ## Then calculate its inverse using Solve(...) and store it in 'm'.
                message("Feels like the first time...")
                original_matrix <- x$get()
                m <- solve(original_matrix)
        
        ## Use the setinverse(...) function in 'x' to cache result as a new 'm'.
                x$setinverse(m)
        
        ## Return the inverse matrix 'm'.
                m
}
